name: Test Push

on:
  pull_request:
    branches: ["main"]
  push:
    paths: ["Code/**"]
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: run
        run: make run
